# Generated by Django 2.1.5 on 2019-01-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share2go', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='note_description',
        ),
        migrations.AddField(
            model_name='note',
            name='note_title',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
