# Generated by Django 2.1.5 on 2019-01-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share2go', '0002_auto_20190126_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
